# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-26 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='diffQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitnv', models.CharField(max_length=100)),
                ('seccode', models.CharField(max_length=100)),
                ('trustFee', models.CharField(max_length=100)),
                ('accumulatedUnitnv', models.CharField(max_length=100)),
                ('manageFee', models.CharField(max_length=100)),
            ],
        ),
    ]
